version: '3'
services:
  auth:
    build: auth/.
    ports:
      - "8001"
  student:
    build: student/.
    ports:
      - "8002"
  teacher:
    build: teacher/.
    ports:
      - "8003"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  db:
    driver: local
